TITLE DISPLAY ASCII CHARACTERS FROM 32 TO 127 ON WINDOW (5,10) AND (20,70)
    .MODEL SMALL
    .STACK 32
.DATA
    SROW   DB 5
    SCOL   DB 10
    EROW   DB 20
    ECOL   DB 70
    SASCII DB 32
    EASCII DB 127
    COLOR  DB 1FH
.CODE
MAIN PROC FAR
         MOV AX,@DATA
         MOV DS,AX




         MOV AX,4C00H
         INT 21H
MAIN ENDP
    END MAIN