TITLE CHANGE THE DATA TO DECIMAL ASCII AND STORE IT IN ANOTHER TABLE
    .MODEL SMALL
    .STACK 32
.DATA
    TABLE DB 0,1,2,3,4,5,6,7,8,9
.CODE
MAIN PROC FAR
         MOV AX,@DATA
         MOV DS,AX




         MOV AX,4C00H
         INT 21H
MAIN ENDP
    END MAIN